# 서울시 지하철 빅데이터 분석

## 1.1 파일 옮기기

In [4]:
%ls C:\Users\tkfka\opensource\data

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 5C34-0912

 C:\Users\tkfka\opensource\data 디렉터리

2025-06-14  오후 07:45    <DIR>          .
2025-06-14  오후 08:23    <DIR>          ..
2025-06-14  오후 07:29        27,184,442 서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv
               1개 파일          27,184,442 바이트
               2개 디렉터리  126,493,974,528 바이트 남음

## 1.2 데이터 로드

In [6]:
import pandas as pd

In [7]:
df_subway = pd.read_csv("C:/Users/tkfka/opensource/data/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv", encoding = "euc-kr")
df_subway.shape

(74277, 52)

In [8]:
df_subway.head()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202505,1호선,동대문,695,16,11411,1920,9784,7385,16724,...,9851,903,3141,8,284,0,0,0,0,20250603
1,202505,1호선,동묘앞,148,3,2859,986,4018,5686,8874,...,4711,135,2029,3,178,0,0,0,0,20250603
2,202505,1호선,서울역,688,67,10783,10374,28788,65184,90177,...,32808,4299,8636,18,174,0,0,0,0,20250603
3,202505,1호선,시청,121,3,1938,5755,3754,27708,7542,...,3883,558,899,0,32,0,0,0,0,20250603
4,202505,1호선,신설동,414,32,9502,2362,10403,9078,22203,...,9707,444,3017,0,0,0,0,0,0,20250603

In [9]:
df_subway.tail()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
74272,201501,중앙선,운길산,0,0,177,56,642,403,1292,...,633,3,222,0,0,0,0,0,0,20151223
74273,201501,중앙선,원덕,1,0,292,4,415,46,537,...,383,3,157,0,0,0,0,0,0,20151223
74274,201501,중앙선,중랑,14,1,4929,424,8539,2084,22160,...,6501,86,1617,0,0,0,0,0,0,20151223
74275,201501,중앙선,팔당,0,0,161,50,368,149,1227,...,336,8,85,0,0,0,0,0,0,20151223
74276,201501,중앙선,회기,436,3,10929,3067,23317,10430,65043,...,35702,767,9314,0,0,0,0,0,0,20151223

## 1.3 데이터 요약

In [11]:
df_subway.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74277 entries, 0 to 74276
Data columns (total 52 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   사용월           74277 non-null  int64
 1   호선명           74277 non-null  object
 2   지하철역          74277 non-null  object
 3   04시-05시 승차인원  74277 non-null  int64
 4   04시-05시 하차인원  74277 non-null  int64
 5   05시-06시 승차인원  74277 non-null  int64
 6   05시-06시 하차인원  74277 non-null  int64
 7   06시-07시 승차인원  74277 non-null  int64
 8   06시-07시 하차인원  74277 non-null  int64
 9   07시-08시 승차인원  74277 non-null  int64
 10  07시-08시 하차인원  74277 non-null  int64
 11  08시-09시 승차인원  74277 non-null  int64
 12  08시-09시 하차인원  74277 non-null  int64
 13  09시-10시 승차인원  74277 non-null  int64
 14  09시-10시 하차인원  74277 non-null  int64
 15  10시-11시 승차인원  74277 non-null  int64
 16  10시-11시 하차인원  74277 non-null  int64
 17  11시-12시 승차인원  74277 non-null  int64
 18  11시-12시 하차인원  74277 non-null  int64
 19  12시-13시 승차인원  74277 non-null  int64
 20  12시-13시 하차인원  74277 non-null  int64
 21  13시-14시 승차인원  74277 non-null  int64
 22  13시-14시 하차인원  74277 non-null  int64
 23  14시-15시 승차인원  74277 non-null  int64
 24  14시-15시 하차인원  74277 non-null  int64
 25  15시-16시 승차인원  74277 non-null  int64
 26  15시-16시 하차인원  74277 non-null  int64
 27  16시-17시 승차인원  74277 non-null  int64
 28  16시-17시 하차인원  74277 non-null  int64
 29  17시-18시 승차인원  74277 non-null  int64
 30  17시-18시 하차인원  74277 non-null  int64
 31  18시-19시 승차인원  74277 non-null  int64
 32  18시-19시 하차인원  74277 non-null  int64
 33  19시-20시 승차인원  74277 non-null  int64
 34  19시-20시 하차인원  74277 non-null  int64
 35  20시-21시 승차인원  74277 non-null  int64
 36  20시-21시 하차인원  74277 non-null  int64
 37  21시-22시 승차인원  74277 non-null  int64
 38  21시-22시 하차인원  74277 non-null  int64
 39  22시-23시 승차인원  74277 non-null  int64
 40  22시-23시 하차인원  74277 non-null  int64
 41  23시-24시 승차인원  74277 non-null  int64
 42  23시-24시 하차인원  74277 non-null  int64
 43  00시-01시 승차인원  74277 non-null  int64
 44  00시-01시 하차인원  74277 non-null  int64
 45  01시-02시 승차인원  74277 non-null  int64
 46  01시-02시 하차인원  74277 non-null  int64
 47  02시-03시 승차인원  74277 non-null  int64
 48  02시-03시 하차인원  74277 non-null  int64
 49  03시-04시 승차인원  74277 non-null  int64
 50  03시-04시 하차인원  74277 non-null  int64
 51  작업일자          74277 non-null  int64
dtypes: int64(50), object(2)
memory usage: 29.5+ MB

## 1.4 결측치 확인

In [13]:
df_subway.isnull()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74272,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74273,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74274,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74275,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74276,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
df_subway.isnull().sum()

사용월             0
호선명             0
지하철역            0
04시-05시 승차인원    0
04시-05시 하차인원    0
05시-06시 승차인원    0
05시-06시 하차인원    0
06시-07시 승차인원    0
06시-07시 하차인원    0
07시-08시 승차인원    0
07시-08시 하차인원    0
08시-09시 승차인원    0
08시-09시 하차인원    0
09시-10시 승차인원    0
09시-10시 하차인원    0
10시-11시 승차인원    0
10시-11시 하차인원    0
11시-12시 승차인원    0
11시-12시 하차인원    0
12시-13시 승차인원    0
12시-13시 하차인원    0
13시-14시 승차인원    0
13시-14시 하차인원    0
14시-15시 승차인원    0
14시-15시 하차인원    0
15시-16시 승차인원    0
15시-16시 하차인원    0
16시-17시 승차인원    0
16시-17시 하차인원    0
17시-18시 승차인원    0
17시-18시 하차인원    0
18시-19시 승차인원    0
18시-19시 하차인원    0
19시-20시 승차인원    0
19시-20시 하차인원    0
20시-21시 승차인원    0
20시-21시 하차인원    0
21시-22시 승차인원    0
21시-22시 하차인원    0
22시-23시 승차인원    0
22시-23시 하차인원    0
23시-24시 승차인원    0
23시-24시 하차인원    0
00시-01시 승차인원    0
00시-01시 하차인원    0
01시-02시 승차인원    0
01시-02시 하차인원    0
02시-03시 승차인원    0
02시-03시 하차인원    0
03시-04시 승차인원    0
03시-04시 하차인원    0
작업일자            0
dtype: int64

# 2 데이터 전처리1

## 2.1 지하철역의 위경도 파악

### googlegeocoding API 사용

In [18]:
import pandas as pd
subway_station = pd.read_csv("C:/Users/tkfka/opensource/data/서울시 지하철 호선별 역별 시간대별 승하차 인원 정보.csv", encoding = "euc-kr")

#몇 호선인지와 지하철 역명 출력
subway_station = subway_station.loc[subway_station['사용월']==202505,:]
subway_station = subway_station[['호선명','지하철역']]

subway_station.head()

   호선명 지하철역
0  1호선  동대문
1  1호선  동묘앞
2  1호선  서울역
3  1호선   시청
4  1호선  신설동

In [19]:
subway_station.describe()

        호선명 지하철역
count   621  621
unique   27  529
top     5호선  서울역
freq     56    5

In [20]:
# 뒤에 + "역"을 붙임
for i in subway_station.index:
    station=''.join(list(subway_station.loc[i,['지하철역']]))
    if station[-1] != '역':
        subway_station.loc[i,['지하철역']] = station+'역'

import googlemaps
my_key = "**********************"
maps = googlemaps.Client(key=my_key)
lat = []  #위도
lng = []  #경도

# 위치를 찾을 장소나 주소를 넣어줌
places = list(subway_station['지하철역'])

i=0
for place in places:   
    i = i + 1
    try:
        geo_location = maps.geocode(place)[0].get('geometry')
        lat .append(geo_location['location']['lat'])
        lng.append(geo_location['location']['lng'])
        

    except:
        lat.append('')
        lng.append('')
        print("%d번 인덱스 위치를 찾는데 실패했습니다."%(i))


# 데이터프레임 만들어 출력
dataframe = pd.DataFrame({'위도':lat, '경도':lng}, index=places)
print(dataframe)

27번 인덱스 위치를 찾는데 실패했습니다.
106번 인덱스 위치를 찾는데 실패했습니다.
128번 인덱스 위치를 찾는데 실패했습니다.
153번 인덱스 위치를 찾는데 실패했습니다.
182번 인덱스 위치를 찾는데 실패했습니다.
193번 인덱스 위치를 찾는데 실패했습니다.
196번 인덱스 위치를 찾는데 실패했습니다.
200번 인덱스 위치를 찾는데 실패했습니다.
208번 인덱스 위치를 찾는데 실패했습니다.
244번 인덱스 위치를 찾는데 실패했습니다.
274번 인덱스 위치를 찾는데 실패했습니다.
444번 인덱스 위치를 찾는데 실패했습니다.
575번 인덱스 위치를 찾는데 실패했습니다.
             위도          경도
동대문역  37.571731  127.011069
동묘앞역  37.573246  127.016589
서울역   37.555946  126.972317
시청역   37.565704  126.976862
신설동역  37.575326   127.02485
...         ...         ...
원덕역   37.468573   127.54716
중랑역   37.594904  127.075833
지평역   37.476818  127.628907
팔당역   37.547376  127.243813
회기역   37.589756  127.057977

[621 rows x 2 columns]

In [21]:
# 결측치(빈 문자열)인 행만 고르기
missing = dataframe[(dataframe['위도'] == '') | (dataframe['경도'] == '')]

# 결과 출력
print(f"결측치가 있는 역 개수: {len(missing)}\n")
print(missing)

결측치가 있는 역 개수: 13

            위도 경도
삼성(무역센터)역
삼각지(전쟁기념관)역
광나루(장신대)역
신정(은행정)역
대흥(서강대앞)역
삼각지(전쟁기념관)역
새절(신사)역
안암(고대병원앞)역
증산(명지대앞)역
온수(성공회대입구)역
암사역사공원역
온수(성공회대입구)역
삼양역

## 2.2 동일한 역과 결측치의 위, 경도 수정

In [23]:
subway_station['위도']=lat
subway_station['경도']=lng

# 동일한 역 처리
subway_station.loc[(subway_station['지하철역']=='양평역')&(subway_station['호선명']=='5호선'),['위도']]= 37.526226
subway_station.loc[(subway_station['지하철역']=='양평역')&(subway_station['호선명']=='5호선'),['경도']]= 126.8844202

subway_station.loc[(subway_station['지하철역']=='양평역')&(subway_station['호선명']=='중앙선'),['위도']]= 37.4927357
subway_station.loc[(subway_station['지하철역']=='양평역')&(subway_station['호선명']=='중앙선'),['경도']]= 127.4896358

# 위도 경도 못찾는 역 삽입
subway_station.loc[(subway_station['지하철역']=='삼성(무역센터)역'),['위도']]= 37.5088595
subway_station.loc[(subway_station['지하철역']=='삼성(무역센터)역'),['경도']]= 127.0630845

subway_station.loc[(subway_station['지하철역']=='삼각지(전쟁기념관)역'),['위도']]= 37.5344385
subway_station.loc[(subway_station['지하철역']=='삼각지(전쟁기념관)역'),['경도']]= 126.9730159

subway_station.loc[(subway_station['지하철역']=='광나루(장신대)역'),['위도']]= 37.5453192
subway_station.loc[(subway_station['지하철역']=='광나루(장신대)역'),['경도']]= 127.1036341

subway_station.loc[(subway_station['지하철역']=='신정(은행정)역'),['위도']]= 37.5249835
subway_station.loc[(subway_station['지하철역']=='신정(은행정)역'),['경도']]= 126.8561815

subway_station.loc[(subway_station['지하철역']=='대흥(서강대앞)역'),['위도']]= 37.5476989
subway_station.loc[(subway_station['지하철역']=='대흥(서강대앞)역'),['경도']]= 126.9423126

subway_station.loc[(subway_station['지하철역']=='새절(신사)역'),['위도']]= 37.5910387
subway_station.loc[(subway_station['지하철역']=='새절(신사)역'),['경도']]= 126.9136157

subway_station.loc[(subway_station['지하철역']=='안암(고대병원앞)역'),['위도']]= 37.5862927
subway_station.loc[(subway_station['지하철역']=='안암(고대병원앞)역'),['경도']]= 127.0291599

subway_station.loc[(subway_station['지하철역']=='증산(명지대앞)역'),['위도']]= 37.5839312
subway_station.loc[(subway_station['지하철역']=='증산(명지대앞)역'),['경도']]= 126.9096997

subway_station.loc[(subway_station['지하철역']=='온수(성공회대입구)역'),['위도']]= 37.4923958
subway_station.loc[(subway_station['지하철역']=='온수(성공회대입구)역'),['경도']]= 126.8239709

subway_station.loc[(subway_station['지하철역']=='암사역사공원역'),['위도']]= 37.5572041
subway_station.loc[(subway_station['지하철역']=='암사역사공원역'),['경도']]= 127.1376821

subway_station.loc[(subway_station['지하철역']=='삼양역'),['위도']]= 37.6268124
subway_station.loc[(subway_station['지하철역']=='삼양역'),['경도']]= 127.0181843

## 2.3 folium 라이브러리 사용

In [25]:
import folium

In [26]:
# 서울시 중심부의 위도, 경도 입니다.
center = [37.541, 126.986]

# 맵이 center 에 위치하고, zoom 레벨은 11로 시작하는 맵 m을 만듭니다.
m = folium.Map(location=center, zoom_start=10)
# 컬러 딕셔너리 (6호선 색깔이 없어서 검정으로 대체)
c_dic = {'1호선':'darkblue','2호선':'green','3호선':'orange','4호선':'lightblue','5호선':'darkpurple','6호선':'orange','7호선':'darkgreen','8호선':'pink','9호선':'beige','중앙선':'blue',
        '9호선2~3단계':'beige','경강선':'cadetblue','경부선':'cadetblue','경원선':'cadetblue','경의선':'cadetblue','경인선':'cadetblue','경춘선':'blue','공항철도 1호선':'cadetblue','과천선':'cadetblue','분당선':'lightred'
         ,'수인선':'lightred','신림선':'lightred','서해선':'gray','안산선':'red','우이신설선':'cadetblue','일산선':'red','장항선':'cadetblue'}

# Choropleth 레이어를 만들고, 맵 m에 추가합니다.
for i in subway_station.index:
    folium.Marker(
        location = list(subway_station.loc[i,['위도', '경도']]),
        popup = subway_station.loc[i, '지하철역'],
        icon=folium.Icon(color=c_dic[subway_station.loc[i, '호선명']],icon='star')
    ).add_to(m)

# 맵 m을 저장
m.save('map.html')

### 2.3.1 csv저장

In [28]:
subway_station.to_csv("서울교통공사_역주소_위경도.csv",index=False)

# 3. 데이터 전처리2

## 3.1 날짜지정: 2025년 1월 부터 2025년 5월까지의 자료만 사용

In [31]:
# 2025년 1월 그 전 데이터는 제외
for i in df_subway.index:
    if df_subway.loc[i, '사용월'] == 202412:
        break

df_subway = df_subway.loc[:3103,:]
df_subway.shape

# csv 저장
df_subway.to_csv("서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202501까지.csv", index=False)

# 4. 데이터 분석

In [33]:
print(df_subway.columns.tolist())

['사용월', '호선명', '지하철역', '04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원', '05시-06시 하차인원', '06시-07시 승차인원', '06시-07시 하차인원', '07시-08시 승차인원', '07시-08시 하차인원', '08시-09시 승차인원', '08시-09시 하차인원', '09시-10시 승차인원', '09시-10시 하차인원', '10시-11시 승차인원', '10시-11시 하차인원', '11시-12시 승차인원', '11시-12시 하차인원', '12시-13시 승차인원', '12시-13시 하차인원', '13시-14시 승차인원', '13시-14시 하차인원', '14시-15시 승차인원', '14시-15시 하차인원', '15시-16시 승차인원', '15시-16시 하차인원', '16시-17시 승차인원', '16시-17시 하차인원', '17시-18시 승차인원', '17시-18시 하차인원', '18시-19시 승차인원', '18시-19시 하차인원', '19시-20시 승차인원', '19시-20시 하차인원', '20시-21시 승차인원', '20시-21시 하차인원', '21시-22시 승차인원', '21시-22시 하차인원', '22시-23시 승차인원', '22시-23시 하차인원', '23시-24시 승차인원', '23시-24시 하차인원', '00시-01시 승차인원', '00시-01시 하차인원', '01시-02시 승차인원', '01시-02시 하차인원', '02시-03시 승차인원', '02시-03시 하차인원', '03시-04시 승차인원', '03시-04시 하차인원', '작업일자']

## 승차인원

In [35]:
# 데이터 load
df_subway = pd.read_csv('서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202501까지.csv')

# 승차 관련 컬럼만 필터링
in_subway= df_subway.columns.tolist()[:3]
for a in df_subway.columns.tolist():
    if a.find('승차')!= -1 :
        in_subway.append(a)

in_subway_df = df_subway[in_subway]

in_subway_df.head()

,사용월,호선명,지하철역,04시-05시 승차인원,05시-06시 승차인원,06시-07시 승차인원,07시-08시 승차인원,08시-09시 승차인원,09시-10시 승차인원,10시-11시 승차인원,...,18시-19시 승차인원,19시-20시 승차인원,20시-21시 승차인원,21시-22시 승차인원,22시-23시 승차인원,23시-24시 승차인원,00시-01시 승차인원,01시-02시 승차인원,02시-03시 승차인원,03시-04시 승차인원
0,202505,1호선,동대문,695,11411,9784,16724,22729,22058,19975,...,25641,19867,17606,15411,12070,6108,903,8,0,0
1,202505,1호선,동묘앞,148,2859,4018,8874,14014,12934,14772,...,25464,13532,6943,5587,4091,1539,135,3,0,0
2,202505,1호선,서울역,688,10783,28788,90177,151470,121799,107330,...,252289,144704,106540,111385,75904,40326,4299,18,0,0
3,202505,1호선,시청,121,1938,3754,7542,10220,13232,16110,...,156643,62998,58654,50245,30412,9887,558,0,0,0
4,202505,1호선,신설동,414,9502,10403,22203,32851,23382,21078,...,51467,21232,15014,13569,9296,4003,444,0,0,0

In [36]:
# 2025.01 ~ 2025.05까지 합하여 승차가 제일 많은 곳
# 호선별
station_group=in_subway_df.groupby(['호선명','지하철역']).sum()
station_group=station_group.drop(['사용월'],axis=1)

### 1호선

In [38]:
station_group.loc['1호선'].style.background_gradient()

### 2호선

In [40]:
station_group.loc['2호선'].style.background_gradient()

### 3호선

In [42]:
station_group.loc['3호선'].style.background_gradient()

### 4호선

In [44]:
station_group.loc['4호선'].style.background_gradient()

### 5호선

In [46]:
station_group.loc['5호선'].style.background_gradient()

### 6호선

In [48]:
station_group.loc['6호선'].style.background_gradient()

### 7호선

In [50]:
station_group.loc['7호선'].style.background_gradient()

### 8호선

In [52]:
station_group.loc['8호선'].style.background_gradient()

### 9호선

In [54]:
station_group.loc['9호선'].style.background_gradient()

### 9호선2~3단계

In [56]:
station_group.loc['9호선2~3단계'].style.background_gradient()

### 경강선

In [58]:
station_group.loc['경강선'].style.background_gradient()

### 경부선

In [60]:
station_group.loc['경부선'].style.background_gradient()

### 경원선

In [62]:
station_group.loc['경원선'].style.background_gradient()

### 경의선

In [64]:
station_group.loc['경의선'].style.background_gradient()

### 경인선

In [66]:
station_group.loc['경인선'].style.background_gradient()

### 경춘선

In [68]:
station_group.loc['경춘선'].style.background_gradient()

### 공항철도 1호선

In [70]:
station_group.loc['공항철도 1호선'].style.background_gradient()

### 과천선

In [72]:
station_group.loc['과천선'].style.background_gradient()

### 분당선

In [74]:
station_group.loc['분당선'].style.background_gradient()

### 서해선

In [76]:
station_group.loc['서해선'].style.background_gradient()

### 수인선

In [78]:
station_group.loc['수인선'].style.background_gradient()

### 신림선

In [80]:
station_group.loc['신림선'].style.background_gradient()

### 안산선

In [82]:
station_group.loc['안산선'].style.background_gradient()

### 우이신설선

In [84]:
station_group.loc['우이신설선'].style.background_gradient()

### 일산선

In [86]:
station_group.loc['일산선'].style.background_gradient()

### 장항선

In [88]:
station_group.loc['장항선'].style.background_gradient()

### 중앙선

In [90]:
station_group.loc['중앙선'].style.background_gradient()

In [91]:
import pandas as pd
from folium.plugins import HeatMap
import folium

# 5개월 합·일평균 계산 (기존과 동일) —#
days = {202501:31, 202502:28, 202503:31, 202504:30, 202505:31}
total_days = sum(days.values())

period_df = df_subway[
    (df_subway['사용월'] >= 202501) &
    (df_subway['사용월'] <= 202505)
].copy()

# '승차' 컬럼 합 → 월별_승차합계
boarding_cols = [c for c in period_df.columns if '승차' in c]
period_df['월별_승차합계'] = period_df[boarding_cols].sum(axis=1)

# 역별 5개월 합 → 하루평균승차
station_tot = (
    period_df
    .groupby('지하철역', as_index=False)['월별_승차합계']
    .sum()
)
station_tot['하루평균승차'] = station_tot['월별_승차합계'] / total_days

# CSV에서 좌표 불러와 전처리 —#
coords = pd.read_csv("서울교통공사_역주소_위경도.csv", dtype=str)

# 역 이름 포맷 통일: 뒤에 '역' 붙이기 (뭐가 문제야!!!!!!!!!!!!!!!!!!!!!!!!!!!)
# station_tot의 역 이름과 서울교통공사_역주소_위경도.csv의 역 이름이 정확히 일치하지 않아서, 병합(merge)이 한 역에 대해서만 성공했고 그 역의 좌표가 시간대 개수(5개)만큼 중복 매칭
coords['지하철역'] = coords['지하철역'].str.strip()
station_tot['지하철역'] = station_tot['지하철역'].astype(str).apply(
    lambda x: x + '역' if not x.endswith('역') else x
)

# 중복된 역 이름은 하나만 남기기
coords = coords.drop_duplicates(subset='지하철역', keep='first')

# 위·경도 → 숫자형, NaN 제거
coords['위도'] = pd.to_numeric(coords['위도'], errors='coerce')
coords['경도'] = pd.to_numeric(coords['경도'], errors='coerce')
coords = coords.dropna(subset=['위도','경도'])

# 병합 & 중복 좌표 한번 더 제거 —#
heat_df = pd.merge(
    station_tot[['지하철역','하루평균승차']],
    coords[['지하철역','위도','경도']],
    on='지하철역',
    how='inner'
)

# 혹시 동일 좌표가 남아 있다면
heat_df = heat_df.drop_duplicates(subset=['위도','경도'])

print(f"HeatMap에 들어갈 포인트 개수: {len(heat_df)}")  # → 수백 개 나와야 정상

# HeatMap 그리기 —#
heat_data = heat_df[['위도','경도','하루평균승차']].values.tolist()

m = folium.Map(location=[37.541, 126.986], zoom_start=11)
HeatMap(
    heat_data,
    radius=15,
    blur=25,
    max_zoom=12
).add_to(m)
m.save('202501-05_역별_하루평균승차_heatmap_corrected.html')

HeatMap에 들어갈 포인트 개수: 527

## 하차인원

In [93]:
df_subway = pd.read_csv('서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202501까지.csv')

# 하차 관련 컬럼만 필터링
out_subway= df_subway.columns.tolist()[:3]
for a in df_subway.columns.tolist():
    if a.find('하차')!= -1 :
        out_subway.append(a)

out_subway_df = df_subway[out_subway]

out_subway_df.head()

,사용월,호선명,지하철역,04시-05시 하차인원,05시-06시 하차인원,06시-07시 하차인원,07시-08시 하차인원,08시-09시 하차인원,09시-10시 하차인원,10시-11시 하차인원,...,18시-19시 하차인원,19시-20시 하차인원,20시-21시 하차인원,21시-22시 하차인원,22시-23시 하차인원,23시-24시 하차인원,00시-01시 하차인원,01시-02시 하차인원,02시-03시 하차인원,03시-04시 하차인원
0,202505,1호선,동대문,16,1920,7385,13140,20497,23012,25358,...,23523,22819,16985,15450,15180,9851,3141,284,0,0
1,202505,1호선,동묘앞,3,986,5686,11760,24066,19657,26787,...,13959,9798,6785,6811,6995,4711,2029,178,0,0
2,202505,1호선,서울역,67,10374,65184,127458,241420,173299,107071,...,173736,119129,88200,82681,62690,32808,8636,174,0,0
3,202505,1호선,시청,3,5755,27708,74917,197607,92400,51960,...,26202,13978,9328,8165,5957,3883,899,32,0,0
4,202505,1호선,신설동,32,2362,9078,25943,53520,32022,21757,...,31725,23013,17361,16853,14996,9707,3017,0,0,0

In [94]:
# 2025.01 ~ 2025.05까지 합하여 하자가 제일 많은 곳
# 호선별
station_group=out_subway_df.groupby(['호선명','지하철역']).sum()
station_group=station_group.drop(['사용월'],axis=1)

In [95]:
station_group.loc['1호선'].style.background_gradient()

In [96]:
station_group.loc['2호선'].style.background_gradient()

In [97]:
station_group.loc['3호선'].style.background_gradient()

In [98]:
station_group.loc['4호선'].style.background_gradient()

In [99]:
station_group.loc['5호선'].style.background_gradient()

In [100]:
station_group.loc['6호선'].style.background_gradient()

In [101]:
station_group.loc['7호선'].style.background_gradient()

In [102]:
station_group.loc['8호선'].style.background_gradient()

In [103]:
station_group.loc['9호선'].style.background_gradient()

In [104]:
station_group.loc['9호선2~3단계'].style.background_gradient()

In [105]:
station_group.loc['경강선'].style.background_gradient()

In [106]:
station_group.loc['경부선'].style.background_gradient()

In [107]:
station_group.loc['경원선'].style.background_gradient()

In [108]:
station_group.loc['경의선'].style.background_gradient()

In [109]:
station_group.loc['경인선'].style.background_gradient()

In [110]:
station_group.loc['경춘선'].style.background_gradient()

In [111]:
station_group.loc['공항철도 1호선'].style.background_gradient()

In [112]:
station_group.loc['과천선'].style.background_gradient()

In [113]:
station_group.loc['분당선'].style.background_gradient()

In [114]:
station_group.loc['서해선'].style.background_gradient()

In [115]:
station_group.loc['수인선'].style.background_gradient()

In [116]:
station_group.loc['신림선'].style.background_gradient()

In [117]:
station_group.loc['안산선'].style.background_gradient()

In [118]:
station_group.loc['우이신설선'].style.background_gradient()

In [119]:
station_group.loc['일산선'].style.background_gradient()

In [120]:
station_group.loc['장항선'].style.background_gradient()

In [121]:
station_group.loc['중앙선'].style.background_gradient()

In [122]:
import pandas as pd
from folium.plugins import HeatMap
import folium

# 0) 기간·일수 설정
days = {202501:31, 202502:28, 202503:31, 202504:30, 202505:31}
total_days = sum(days.values())

# 1) 2025.01~05 데이터만 필터링
period_df = df_subway[
    (df_subway['사용월'] >= 202501) &
    (df_subway['사용월'] <= 202505)
].copy()

# 2) “하차” 관련 컬럼만 추출하여 월별 하차 합계 계산
alight_cols = [c for c in period_df.columns if '하차' in c]
period_df['월별_하차합계'] = period_df[alight_cols].sum(axis=1)

# 3) 역별 5개월 합 → 일평균 하차량
alight_tot = (
    period_df
    .groupby('지하철역', as_index=False)['월별_하차합계']
    .sum()
)
alight_tot['하루평균하차'] = alight_tot['월별_하차합계'] / total_days

# 4) CSV에서 위·경도 로드 & 전처리
coords = pd.read_csv("서울교통공사_역주소_위경도.csv", dtype=str)
coords['지하철역'] = coords['지하철역'].str.strip()
# station_tot 에도 '역'이 붙어있도록 통일
alight_tot['지하철역'] = alight_tot['지하철역'].apply(
    lambda x: x + '역' if not x.endswith('역') else x
)
# 중복 행 제거, 숫자형 변환, NaN 행 제거
coords = coords.drop_duplicates(subset='지하철역', keep='first')
coords['위도'] = pd.to_numeric(coords['위도'], errors='coerce')
coords['경도'] = pd.to_numeric(coords['경도'], errors='coerce')
coords = coords.dropna(subset=['위도','경도'])

# 5) 병합 & 중복 좌표 제거
heat_df_alight = pd.merge(
    alight_tot[['지하철역','하루평균하차']],
    coords[['지하철역','위도','경도']],
    on='지하철역',
    how='inner'
).drop_duplicates(subset=['위도','경도'])
print(f"HeatMap 포인트 수: {len(heat_df_alight)}")

# 6) HeatMap용 리스트 생성
heat_data = heat_df_alight[['위도','경도','하루평균하차']].values.tolist()

# 7) 지도 생성 및 레이어 추가
m = folium.Map(location=[37.541, 126.986], zoom_start=11)
HeatMap(
    heat_data,
    radius=15,    # 반경
    blur=25,      # 블러 강도
    max_zoom=12
).add_to(m)

# 8) 결과 저장
m.save('202501-05_역별_하루평균하차_heatmap.html')

HeatMap 포인트 수: 527

## 2025년 5월 데이터의 시간에 따른 에니메이션 히트맵

## 승차

In [125]:
import pandas as pd
from folium.plugins import HeatMapWithTime
import folium

# 1. 파일 경로
subway_path = "서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202501까지.csv"
coords_path = "서울교통공사_역주소_위경도.csv"

# 2. 데이터 불러오기
df_subway = pd.read_csv(subway_path)
coords = pd.read_csv(coords_path)

# 3. 2025년 5월 데이터 필터링 + 승차 인원 컬럼만 선택
df_subway = df_subway[df_subway['사용월'] == 202505].copy()
boarding_cols = [c for c in df_subway.columns if '승차' in c]
df_filtered = df_subway[['호선명', '지하철역'] + boarding_cols].copy()

# 4. 지하철역 이름 정리 (좌표 파일과 병합 시 일치시키기)
coords['지하철역'] = coords['지하철역'].str.strip()
df_filtered['지하철역'] = df_filtered['지하철역'].astype(str).apply(
    lambda x: x + '역' if not x.endswith('역') else x
)

# 5. 위경도 정제 및 병합
coords['위도'] = pd.to_numeric(coords['위도'], errors='coerce')
coords['경도'] = pd.to_numeric(coords['경도'], errors='coerce')
coords = coords.dropna(subset=['위도', '경도'])

df_merged = pd.merge(df_filtered, coords, on='지하철역', how='inner')

# 6. 시간대별 히트맵 데이터 생성
heatmap_data = []
time_labels = []

for col in boarding_cols:
    temp = df_merged[['위도', '경도', col]].copy()
    temp.columns = ['위도', '경도', '승차인원']
    heatmap_data.append(temp.values.tolist())
    time_labels.append(col.replace(' 승차인원', ''))

# 7. Folium 지도 + 애니메이션 히트맵
m = folium.Map(location=[37.541, 126.986], zoom_start=11)

HeatMapWithTime(
    data=heatmap_data,
    index=time_labels,
    auto_play=True,
    max_opacity=0.8,
    radius=12,
    use_local_extrema=True
).add_to(m)

# 8. 저장
m.save("animated_heatmap_승차_202505.html")

## 하차

In [127]:
import pandas as pd
from folium.plugins import HeatMapWithTime
import folium

# 1. 파일 경로 설정
subway_path = "서울시 지하철 호선별 역별 시간대별 승하차 인원 정보_202501까지.csv"
coords_path = "서울교통공사_역주소_위경도.csv"

# 2. 데이터 불러오기
df_subway = pd.read_csv(subway_path)
coords = pd.read_csv(coords_path)

# 3. 2025년 5월 데이터 필터링 + 하차 인원 컬럼만 추출
df_subway = df_subway[df_subway['사용월'] == 202505].copy()
alighting_cols = [c for c in df_subway.columns if '하차' in c]
df_filtered = df_subway[['호선명', '지하철역'] + alighting_cols]

# 4. 지하철역 이름 정리 (좌표 파일과 맞추기)
coords['지하철역'] = coords['지하철역'].str.strip()
df_filtered['지하철역'] = df_filtered['지하철역'].astype(str).apply(
    lambda x: x + '역' if not x.endswith('역') else x
)

# 5. 좌표 데이터 정제
coords['위도'] = pd.to_numeric(coords['위도'], errors='coerce')
coords['경도'] = pd.to_numeric(coords['경도'], errors='coerce')
coords = coords.dropna(subset=['위도', '경도'])

# 6. 지하철 데이터 + 좌표 병합
df_merged = pd.merge(df_filtered, coords, on='지하철역', how='inner')

# 7. 시간대별 히트맵 데이터 리스트 만들기
heatmap_data = []
time_labels = []

for col in alighting_cols:
    temp = df_merged[['위도', '경도', col]].copy()
    temp.columns = ['위도', '경도', '하차인원']
    heatmap_data.append(temp.values.tolist())
    time_labels.append(col.replace(' 하차인원', ''))

# 8. Folium 지도 생성 및 히트맵 추가
m = folium.Map(location=[37.541, 126.986], zoom_start=11)

HeatMapWithTime(
    data=heatmap_data,
    index=time_labels,
    auto_play=True,
    max_opacity=0.8,
    radius=12,
    use_local_extrema=True
).add_to(m)

# 9. 결과 저장
m.save("animated_heatmap_하차_202505.html")

C:\Users\tkfka\AppData\Local\Temp\ipykernel_21884\19051201.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['지하철역'] = df_filtered['지하철역'].astype(str).apply(